import { defineConfig } from 'tsup'

export default defineConfig({
	entry: ['src/index.ts'],
	format: ['cjs', 'esm'],
	dts: {
		resolve: true,
		banner: '// Generated by tsup - do not edit manually\n'
	},
	banner: {
		js: '// Generated by tsup - do not edit manually\n'
	},
	outDir: 'dist',
	splitting: false,
	sourcemap: true,
	clean: true,
	minify: false,
	onSuccess: async () => {
		console.log('✅ @tars/logger build completed successfully')
	}
})
