import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['cjs', 'esm'],
  dts: true,
  clean: true,
  external: [
    // External dependencies that shouldn't be bundled
    '@needle-di/core',
    'obsidian',
    'async-mutex'
  ],
  banner: {
    js: '// Generated by tsup - do not edit manually\n'
  },
  sourcemap: true,
  minify: false,
  target: 'es2020',
  onSuccess: async () => {
    console.log('✅ @tars/contracts build completed successfully')
  }
})