import { defineConfig } from 'tsup'

export default defineConfig({
	entry: [
		'src/index.ts',
		'src/events/index.ts',
		'src/providers/index.ts',
		'src/services/index.ts',
		'src/tokens/index.ts'
	],
	format: ['cjs', 'esm'],
	dts: {
		resolve: true,
		banner: '// Generated by tsup - do not edit manually\n'
	},
	outDir: 'dist',
	clean: true,
	external: [
		// External dependencies that shouldn't be bundled
		'@needle-di/core',
		'obsidian'
	],
	banner: {
		js: '// Generated by tsup - do not edit manually\n'
	},
	sourcemap: true,
	minify: false,
	target: 'es2020',
	onSuccess: async () => {
		console.log('✅ @tars/contracts build completed successfully')
	}
})
